### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by demianrey** [MatsuriDayo/Matsuri#1]
Hi, I would like to know if it is possible for you to give a guide to compile, I tried but I get this error:

Included build 'C:\Users\demia\Android studio\Matsuri\external\editorkit' does not exist.

Regards

**Comment by arm64v8a** [comment]
This project does not support compiling on Windows.

If you encounter problems with compiling on Linux, I can update the instructions. But you'd better try to follow the Actions scripts first.

**Comment by demianrey** [comment]
![image](https://user-images.githubusercontent.com/48655207/148340135-c394795a-0bbc-4845-a60a-9578a6da730c.png)
I can't compile the necessary core, I'm already on Ubuntu, could you tell me how I should execute the scripts please

**Comment by arm64v8a** [comment]
Install golang and run `./run lib core` in the shell.
I am planning to write a compilation tutorial...

**Comment by demianrey** [comment]
> Install golang and run `./run lib core` in the shell. I am planning to write a compilation tutorial...

![image](https://user-images.githubusercontent.com/48655207/148431918-750e8608-7bcf-48f0-b2b4-b7277709e9bc.png)

Thanks for your answer, I did what you said and there the configuration stops

**Comment by arm64v8a** [comment]
I don't know.
Try to update golang to 1.17?

**Comment by demianrey** [comment]
> I don't know. Try to update golang to 1.17?

yes that was the problem, I had golang version 1.16 ... compiled and installed, thank you very much
