### ISSUE TITLE
Issue with duplicate servers

### ISSUE THREAD

**Issue by Mahantor** [MatsuriDayo/Matsuri#13]
Hello
How can I remove duplicate servers? Is this a bug ??? Or am I wrong?

https://user-images.githubusercontent.com/91434001/156515923-d6f0841d-fd00-42a1-976a-2df0e95b1597.mp4

Why it is not possible to delete duplicate servers in basic mode. Can you add this?

**Comment by arm64v8a** [comment]
Try "delete duplicate" in subscription settings

**Comment by Mahantor** [comment]
I tried but this option does not work

**Comment by arm64v8a** [comment]
0.3.4
