### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [MatsuriDayo/Matsuri#16]
https://monitor.f-droid.org/builds/log/moe.matsuri.lite/715#site-footer The same error as the GitHub CI. Could you please take a look? Thanks!

**Comment by arm64v8a** [comment]
https://github.com/MatsuriDayo/Matsuri/tree/0.3.5-fix-fdroid

Try this

**Comment by linsui** [comment]
It builds fine. Thanks!
