### ISSUE TITLE
[Feature request] Add support for shadowsocks-2022 ciphers

### ISSUE THREAD

**Issue by Shikopat** [MatsuriDayo/Matsuri#24]
Please Add support for shadowsocks-2022 ciphers:

2022-BLAKE3-AES-128-GCM
2022-BLAKE3-AES-256-GCM
2022-BLAKE3-CHACHA20-IETF-POLY1305

Regards

**Comment by arm64v8a** [comment]
use SagerNet

I can't find the urgency to add these algorithms

> ss已经没救了
