### ISSUE TITLE
[画饼] Matsuri 0.4.x & Nekoray

### ISSUE THREAD

**Issue by arm64v8a** [MatsuriDayo/Matsuri#27]
## Matsuri 0.4.x

0.4.x 预计跟随上游 v2fly 引入 VLite 协议支持。

目前 v2fly 内的 VLite 协议支持不完整，也没有发布。

## Nekoray

Nekoray 为全新 Linux/Windows 软件，基于 Qt

代理客户端复用了 Matsuri/libcore (同时也是 custom v2ray-core)

前后端通过 grpc 通信，见 `Matsuri/libcore/nekoray_rpc`

前端部分则是从头开始写，UI 上为 SagerNet Qv2ray v2rayN 的缝合，预计可以复刻 Matsuri 的大部分功能。

同样未发布。

**Comment by arm64v8a** [comment]
![image](https://user-images.githubusercontent.com/48624112/165332633-d514b34c-69de-4d4b-a0d2-638a5ae13bd6.png)
![image](https://user-images.githubusercontent.com/48624112/165332602-df3caf47-0ff3-45c2-a3df-af0b5f6c4ded.png)

**Comment by DoveBoy** [comment]
什么时候可以加入一个测节点下载速度的功能？这是个很实用的功能啊

**Comment by JPGC123** [comment]
直接内置核心为xray吧

**Comment by arm64v8a** [comment]
nekoray 已公开
