### ISSUE TITLE
transparent proxy

### ISSUE THREAD

**Issue by SafaSafari** [MatsuriDayo/Matsuri#28]
I need to transparent proxy in matsuri
I know change iptables rules need to su permission
My phone is rooted and when i use transparent proxy, i get permission denied in log
Please add option to enable root permission in matsuri and use transparent proxy
Best regards 🌺

**Comment by arm64v8a** [comment]
transparent proxy doesn't seem to require root

send the full log

**Comment by SafaSafari** [comment]
> transparent proxy (inbound) doesn't seem to require root
> 
> send the full log

[Matsuri 9061125043430461732.log](https://github.com/MatsuriDayo/Matsuri/files/8646538/Matsuri.9061125043430461732.log)

**Comment by arm64v8a** [comment]
`transport/internet: failed to apply socket options to incoming connection > transport/internet: failed to set IP_TRANSPARENT > operation not permitted`

**Comment by arm64v8a** [comment]
ProxyService cannot run as root.

I don't use transparent proxy. Check your iptables rules?

**Comment by SafaSafari** [comment]
[iptables_after.txt](https://github.com/MatsuriDayo/Matsuri/files/8671502/iptables_after.txt)
[iptables_before.txt](https://github.com/MatsuriDayo/Matsuri/files/8671503/iptables_before.txt)
[diff.txt](https://github.com/MatsuriDayo/Matsuri/files/8671504/diff.txt)

Iptables before and after run matsuri in proxy only mode and enabled transparent proxy on REDIRECT mode
