### ISSUE TITLE
Request: Update X-Ray Core Plugin to 1.5.5 

### ISSUE THREAD

**Issue by Shikopat** [MatsuriDayo/Matsuri#29]
Hey Drear dev

please upgrade x-ray core plugin with the latest release of official core:

https://github.com/XTLS/Xray-core/releases/tag/v1.5.5

**Comment by Gherkashen2** [comment]
& Please upgrade V2ray core to newest Release.

**Comment by Gherkashen2** [comment]
V2ray Core 4.45.0
