### ISSUE TITLE
ssh代理不能正常关闭连接

### ISSUE THREAD

**Issue by xxxsen** [MatsuriDayo/Matsuri#30]
使用ssh进行代理, 在关闭连接后(APP主界面右下角的按钮), 发现服务端的链接还保持着, 每次重新连接都会导致一个连接挂着。
![image](https://user-images.githubusercontent.com/3880276/166650642-c1ef2a88-83f8-4067-8acc-74b3cc4d3ff1.png)

只有程序整个关闭后, 才会将连接释放掉(剩下的一个连接不是app打开的)。
![image](https://user-images.githubusercontent.com/3880276/166650937-a823aed9-d0bc-4e70-99ee-ebae6927de16.png)

复现步骤很简单: 部署一个ssh服务器, app端增加ssh配置, 之后运行进行连接、关闭连接, 每操作一次, 必定导致一个连接泄露。

Version: 0.3.8
Version(V2ray-core): v5.0.3-喵

**Comment by xxxsen** [comment]
![image](https://user-images.githubusercontent.com/3880276/166655544-691ec714-3d89-4375-9635-3b46795f007b.png)


另外的一个异常是, 服务端产生到远端的连接也无法正常关闭。
20结尾的ip是ssh的服务端
10结尾的ip是远程dns服务器

app连接到20的服务端后向10发起dns解析, 之后10的机器结束了链接, 但是在20的机器这边链接还被保留着, 进入了close_wait状态, 也就是没有在对端关闭连接后在本地对对应的连接进行关闭(截图中, 这类异常的连接保留了10分钟, 但是后面看, 基本是没有关闭的, 一直挂着)。

**Comment by arm64v8a** [comment]
本地到服务器 22 端口的连接仍然 ESTABLISHED？

ssh 代理部分继承自 SagerNet，可以尝试使用 SagerNet 看看能否复现

**Comment by xxxsen** [comment]
@arm64v8a 对的，在app内关掉代理，服务端链接还是处于ESTABLISHED状态，且没有释放。

sagernet的，我这边也验证下，看有没有问题。

**Comment by xxxsen** [comment]
@arm64v8a sagernet也有上面提到的2个问题。。

**Comment by arm64v8a** [comment]
https://github.com/MatsuriDayo/v2ray-core/commit/eab37241cc10eb593f0331ea3fce74cc6a3b4f0c

经测试，转发的连接关闭后，服务器侧正常进入 TIME_WAIT

**Comment by xxxsen** [comment]
其实 sagernet/v2ray-core@v5.0.9 的时候已经修复了的，但是应用打包的时候用的不是最新的代码，所以有问题。
