### ISSUE TITLE
安全设置tls

### ISSUE THREAD

**Issue by aole1056** [MatsuriDayo/Matsuri#33]
使用文档中 
配置

(TLS) 安全设置
允许不安全连接：启用后安全性相当于明文。
证书（链）：应填入证书内容，通常是 PEM 格式。

这个开关在软件中怎么没有呢 
感觉安全还是很重要的   大佬有时间的时候可以看看吗

**Comment by arm64v8a** [comment]
有

**Comment by aole1056** [comment]
额 非常抱歉  的确在节点编辑里找到了 
感觉这个设置加到 分组 的设置里直接对整个订阅链接的节点生效  这样可以吗
