### ISSUE TITLE
Request to add or change a new URL test strategy

### ISSUE THREAD

**Issue by aaaamirabbas** [MatsuriDayo/Matsuri#34]
Hello, thank you for developing this application.

In my country, some websites like `spotify.com` are banned and I can even be identified by a VPN connection.
In the tests I did, I noticed that some servers have IP or location leaks and services like

`spotify.com`
`developer.android.com`

I get a **403** error message

Please add an option to the URL Test section that will only identify the server as safe if it responds 200 or correctly.

By doing this I can, for example, replace the `spotify.com` website with `cp.cloudflare.com` and then identify servers that can work without leaking my location and IP.

Thanks

**Comment by arm64v8a** [comment]
in 0.3.9 url test http response code is ignored, so the latency shows up even when getting

**Comment by aaaamirabbas** [comment]
@arm64v8a Did you notice what I mean?
The URL Test option is currently unable to detect location leakage.

**Comment by arm64v8a** [comment]
> Please add an option to the URL Test section that will **only identify the server as safe if it responds 200** or correctly.

If you mean this, I won't add.

In this project, "secure" only means that the inner content of the connection (what site you access) will not be leaked to your local ISP.

It **does not** mean that "Bypassing the firewall is undiscoverable" or "The relay server you are connected to is not evil".

翻墙行为可以被轻易判断，用于翻墙的服务器也可能存在劫持等恶意行为。这些都是难以判断的黑箱，所以不会改「不安全提示」的判定。

**Comment by aaaamirabbas** [comment]
@arm64v8a

**Comment by aaaamirabbas** [comment]
@arm64v8a Hello.

**I do not need URL Test to detect location leaks!**

I just need the URL Test not to recognize 403 responses and so on as the correct connection.

This is not very complicated and **SagerNet** is currently using this strategy but it has been disabled or changed in **Matsuri**.

Thanks

**Comment by arm64v8a** [comment]
Yes, this is an intentional change.

对的，这是有意的更改。
