### ISSUE TITLE
Traffic information does not match SSPanel 

### ISSUE THREAD

**Issue by demianrey** [MatsuriDayo/Matsuri#37]
The information of total traffic and remaining traffic is different from that of the panel
![IMG_20220604_083031](https://user-images.githubusercontent.com/48655207/172001447-1c3d0604-38ca-4860-9252-5ab8847e0275.jpg)
![IMG_20220604_083201](https://user-images.githubusercontent.com/48655207/172001675-70ce8211-3d1d-4e8f-84fe-c1b2fe3faa96.jpg)

**Comment by arm64v8a** [comment]
Android displays "GB" in SI units.

**Comment by arm64v8a** [comment]
0.3.11
