### ISSUE TITLE
Trojan線路皆不通，Clash Android卻通

### ISSUE THREAD

**Issue by YheonYeung** [MatsuriDayo/Matsuri#38]
有個訂閲提供Trojan線路，我在Clash windows那邊測PING有結果，連上能用。Matsuri做URL Test全部都不通，選與電腦那邊同樣的線路也無法使用。
我也試過裝Trojan-Go然後把Trojan提供程式選上，URL Test只有逾時、無法使用兩種。
然後我下載Clash Android試下，居然有PING也能打開網頁。
實在無辦法，提個議題反映下。
![image](https://user-images.githubusercontent.com/63342274/172657464-b54b6471-37f6-475c-b7d2-e7015660e426.png)
![image](https://user-images.githubusercontent.com/63342274/172657543-a7ba8746-2215-43e5-845b-9e973c67ad78.png)

**Comment by arm64v8a** [comment]
提供日志

**Comment by YheonYeung** [comment]
> 提供日志

[Matsuri 4301690480656514316「沒改」.log](https://github.com/MatsuriDayo/Matsuri/files/8869952/Matsuri.4301690480656514316.log)
[Matsuri 6027264911077228181「Google DNS & Ping Google」.log](https://github.com/MatsuriDayo/Matsuri/files/8869953/Matsuri.6027264911077228181.Google.DNS.Ping.Google.log)

**Comment by arm64v8a** [comment]
`proxy/trojan: connection ends > proxy/trojan: failed to read address and port > x509: certificate is valid for node.franxx.codes, not telegram.channel.p2psharing`

SNI没有设置对，应该是订阅格式（或者是订阅本身）的问题，换个订阅格式试试。

**Comment by YheonYeung** [comment]
> `proxy/trojan: connection ends > proxy/trojan: failed to read address and port > x509: certificate is valid for node.franxx.codes, not telegram.channel.p2psharing`
> 
> SNI没有设置对，应该是订阅格式（或者是订阅本身）的问题，换个订阅格式试试。

如你所見是他人分享的訂閲，上游我也無法改變什麼(-_-)

**Comment by arm64v8a** [comment]
应该是 clash 格式订阅 skip-cert-verify 没有正确解析，正在修复
