### ISSUE TITLE
测速闪退&vmees节点连接一段时间后会断链接

### ISSUE THREAD

**Issue by fengguowudi** [MatsuriDayo/Matsuri#6]
测速节点时会出现闪退，测试节点数量在100-200之间。
然后建议支持wireguard批量导入

**Comment by fengguowudi** [comment]
且vmees节点连接一段时间后会断链接，但是节点可用，断开重连恢复正常
事例节点
vmess://b82814c6-2b6a-4c15-ae33-a0cc681ee5fb@101.89.109.30:10015/?type=tcp&encryption=auto#%E9%A6%99%E6%B8%AF%E5%8D%83%E5%85%86-03%E5%8F%B7

**Comment by arm64v8a** [comment]
请提供日志
