### ISSUE TITLE
[Help] allowinsecure always true when tls is enabled

### ISSUE THREAD

**Issue by demianrey** [MatsuriDayo/Matsuri#9]
What's up friend, can you help me please, I need allowinsecure to always be on... tell me how to do it?

**Comment by arm64v8a** [comment]
It is **not recommended** to use this way.

I you can modify the app yourself.

**Comment by demianrey** [comment]
> It is **not recommended** to use this way.
> 
> I you can modify the app yourself.

That's what I do, a tweak on my own, but all night before I had no success with this... Tried setting true allowinsecure .in DataStore but it doesn't

**Comment by demianrey** [comment]
solved, modify ConfigBuilder file ;)
